### ISSUE TITLE
Ask paco for his opinion

### ISSUE THREAD

**Issue by steliospapagrigoriou** [steliospapagrigoriou/paco-bot#2]
When someone asks: "right paco?"
paco will reply:`[ "Exactly!", "That's right!", "Oh yeah!"] <user's name>`

**Comment by memosstilvi** [comment]
I don't think paco should always approve.
I propose using a random variable 0 or 1 to disapprove or approve the user
(choose between a list of approval expressions and a list of dissaproval epressions)

**Comment by steliospapagrigoriou** [comment]
nice !

**Comment by benelliott** [comment]
Resolved in ae23783b0f37b1445eabdc829710e4622d415202
