### ISSUE TITLE
Link paco up to the Sonos

### ISSUE THREAD

**Issue by benelliott** [steliospapagrigoriou/paco-bot#3]
Paco's DJ skills need to be put to use.

**Comment by memosstilvi** [comment]
+1 (for the label as well)

Key features:
1. Change volume
2. Stop/start/change song

**Comment by steliospapagrigoriou** [comment]
+1

**Comment by steliospapagrigoriou** [comment]
https://github.com/markhuge/hubot-sonos

**Comment by steliospapagrigoriou** [comment]
DONE BABY!
